baseurl = "/"
languageCode = "en-us"
title = "Kanariefogel"
theme = "xmag"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 6
googleAnalytics = "UA-104971743-1"

[permalinks]
	post = "/post/:year/:month/:day/:slug/"

[params]
    description = "A website built through Hugo and blogdown."
    summary_length = 300
    custom_css = ["/css/custom.css"]
  
[params.text]
    back = "&larr; Hem"
    truncated = "&hellip;"