baseurl = "/"
languageCode = "en-us"
title = "Kanariefogel"
theme = "xmag"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 6

[permalinks]
	post = "/post/:year/:month/:day/:slug/"

[params]
    description = "A website built through Hugo and blogdown."
    summary_length = 300
  
[params.text]
    back = "&larr; Back to Home"
    truncated = "&hellip;"